language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t avivkr/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true avivkr/react-test npm test -- --coverage

after_success:
  - docker build -t avivkr/multi-client ./client
  - docker build -t avivkr/multi-nginx ./nginx
  - docker build -t avivkr/multi-server ./server
  - docker build -t avivkr/multi-worker ./worker
  # Login to he Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push avivkr/multi-client
  - docker push avivkr/multi-nginx
  - docker push avivkr/multi-server
  - docker push avivkr/multi-worker

deploy:
  provide: elasticbeanstalk
  region: ap-northeast-1
  app: complex-docker
  env: Complexdocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-13989246254
  bucket_path: complex-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

